./install/rtl/core/config.v
./install/rtl/core/e203_biu.v
./install/rtl/core/e203_clk_ctrl.v
./install/rtl/core/e203_clkgate.v
./install/rtl/core/e203_core.v
./install/rtl/core/e203_cpu.v
./install/rtl/core/e203_cpu_top.v
./install/rtl/core/e203_defines.v
#./install/rtl/core/e203_dtcm_ctrl.v
./install/rtl/core/e203_dtcm_ram.v
#./install/rtl/core/e203_extend_csr.v
./install/rtl/core/e203_exu.v
./install/rtl/core/e203_exu_alu.v
./install/rtl/core/e203_exu_alu_bjp.v
./install/rtl/core/e203_exu_alu_csrctrl.v
./install/rtl/core/e203_exu_alu_dpath.v
./install/rtl/core/e203_exu_alu_lsuagu.v
./install/rtl/core/e203_exu_alu_muldiv.v
./install/rtl/core/e203_exu_alu_rglr.v
./install/rtl/core/e203_exu_branchslv.v
./install/rtl/core/e203_exu_commit.v
./install/rtl/core/e203_exu_csr.v                                                                                                                                                            ../install/rtl/core/e203_exu_decode.v
./install/rtl/core/e203_exu_disp.v
./install/rtl/core/e203_exu_excp.v
./install/rtl/core/e203_exu_longpwbck.v
./install/rtl/core/e203_exu_oitf.v
./install/rtl/core/e203_exu_regfile.v
./install/rtl/core/e203_exu_wbck.v
./install/rtl/core/e203_ifu.v
./install/rtl/core/e203_ifu_ifetch.v
./install/rtl/core/e203_ifu_ift2icb.v
./install/rtl/core/e203_ifu_litebpu.v
./install/rtl/core/e203_ifu_minidec.v
./install/rtl/core/e203_irq_sync.v
#./install/rtl/core/e203_itcm_ctrl.v
./install/rtl/core/e203_itcm_ram.v
./install/rtl/core/e203_lsu.v
./install/rtl/core/e203_lsu_ctrl.v
./install/rtl/core/e203_reset_ctrl.v
./install/rtl/core/e203_srams.v
./install/rtl/debug/sirv_debug_csr.v  
./install/rtl/debug/sirv_debug_module.v  
./install/rtl/debug/sirv_debug_ram.v  
./install/rtl/debug/sirv_debug_rom.v
./install/rtl/debug/sirv_jtag_dtm.v
./install/rtl/fab/sirv_icb1to16_bus.v
./install/rtl/fab/sirv_icb1to2_bus.v
./install/rtl/fab/sirv_icb1to8_bus.v
#./install/rtl/general/sirv_1cyc_sram_ctrl.v
./install/rtl/general/sirv_gnrl_bufs.v
./install/rtl/general/sirv_gnrl_dffs.v
./install/rtl/general/sirv_gnrl_icbs.v
./install/rtl/general/sirv_gnrl_ram.v
./install/rtl/general/sirv_gnrl_xchecker.v
./install/rtl/general/sirv_sim_ram.v
#./install/rtl/general/sirv_sram_icb_ctrl.v
./install/rtl/mems/sirv_mrom.v  
./install/rtl/mems/sirv_mrom_top.v
./install/rtl/perips/i2c_master_bit_ctrl.v*
./install/rtl/perips/i2c_master_byte_ctrl.v*
./install/rtl/perips/i2c_master_defines.v*
./install/rtl/perips/i2c_master_top.v*
./install/rtl/perips/sirv_AsyncResetReg.v
./install/rtl/perips/sirv_AsyncResetRegVec.v
./install/rtl/perips/sirv_AsyncResetRegVec_1.v
./install/rtl/perips/sirv_AsyncResetRegVec_129.v
./install/rtl/perips/sirv_AsyncResetRegVec_36.v
./install/rtl/perips/sirv_AsyncResetRegVec_67.v
./install/rtl/perips/sirv_DeglitchShiftRegister.v
./install/rtl/perips/sirv_LevelGateway.v
./install/rtl/perips/sirv_ResetCatchAndSync.v
./install/rtl/perips/sirv_ResetCatchAndSync_2.v
./install/rtl/perips/sirv_aon.v
./install/rtl/perips/sirv_aon_lclkgen_regs.v
./install/rtl/perips/sirv_aon_porrst.v
./install/rtl/perips/sirv_aon_top.v
./install/rtl/perips/sirv_aon_wrapper.v
./install/rtl/perips/sirv_clint.v
./install/rtl/perips/sirv_clint_top.v
./install/rtl/perips/sirv_expl_apb_slv.v
./install/rtl/perips/sirv_expl_axi_slv.v
./install/rtl/perips/sirv_flash_qspi.v
./install/rtl/perips/sirv_flash_qspi_top.v
./install/rtl/perips/sirv_gpio.v
./install/rtl/perips/sirv_gpio_top.v
./install/rtl/perips/sirv_hclkgen_regs.v
./install/rtl/perips/sirv_jtaggpioport.v
./install/rtl/perips/sirv_otp_top.v
./install/rtl/perips/sirv_plic_man.v
./install/rtl/perips/sirv_plic_top.v
./install/rtl/perips/sirv_pmu.v
./install/rtl/perips/sirv_pmu_core.v
./install/rtl/perips/sirv_pwm16.v
./install/rtl/perips/sirv_pwm16_core.v
./install/rtl/perips/sirv_pwm16_top.v
./install/rtl/perips/sirv_pwm8.v
./install/rtl/perips/sirv_pwm8_core.v
./install/rtl/perips/sirv_pwm8_top.v
./install/rtl/perips/sirv_pwmgpioport.v
./install/rtl/perips/sirv_qspi_1cs.v
./install/rtl/perips/sirv_qspi_1cs_top.v
./install/rtl/perips/sirv_qspi_4cs.v
./install/rtl/perips/sirv_qspi_4cs_top.v
./install/rtl/perips/sirv_qspi_arbiter.v
./install/rtl/perips/sirv_qspi_fifo.v
./install/rtl/perips/sirv_qspi_media.v
./install/rtl/perips/sirv_qspi_media_1.v
./install/rtl/perips/sirv_qspi_media_2.v
./install/rtl/perips/sirv_qspi_physical.v
./install/rtl/perips/sirv_qspi_physical_1.v
./install/rtl/perips/sirv_qspi_physical_2.v
./install/rtl/perips/sirv_queue.v
./install/rtl/perips/sirv_queue_1.v
./install/rtl/perips/sirv_repeater_6.v
./install/rtl/perips/sirv_rtc.v
./install/rtl/perips/sirv_spi_flashmap.v
./install/rtl/perips/sirv_spigpioport.v
./install/rtl/perips/sirv_spigpioport_1.v
./install/rtl/perips/sirv_spigpioport_2.v
./install/rtl/perips/sirv_tl_repeater_5.v
./install/rtl/perips/sirv_tlfragmenter_qspi_1.v
./install/rtl/perips/sirv_tlwidthwidget_qspi.v
./install/rtl/perips/sirv_uart.v
./install/rtl/perips/sirv_uart_top.v
./install/rtl/perips/sirv_uartgpioport.v
./install/rtl/perips/sirv_uartrx.v
./install/rtl/perips/sirv_uarttx.v
./install/rtl/perips/sirv_wdog.v
./install/rtl/soc/e203_soc_top.v 
./install/rtl/subsys/e203_subsys_clint.v
./install/rtl/subsys/e203_subsys_gfcm.v
./install/rtl/subsys/e203_subsys_hclkgen.v
./install/rtl/subsys/e203_subsys_hclkgen_rstsync.v
./install/rtl/subsys/e203_subsys_main.v
./install/rtl/subsys/e203_subsys_mems.v
./install/rtl/subsys/e203_subsys_perips.v
./install/rtl/subsys/e203_subsys_plic.v
./install/rtl/subsys/e203_subsys_pll.v
./install/rtl/subsys/e203_subsys_pllclkdiv.v
./install/rtl/subsys/e203_subsys_top.v
./install/tb/tb_top.v

